# Generated by Django 3.2.23 on 2023-12-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feed',
        ),
    ]
