# Generated by Django 3.2.23 on 2023-12-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20231230_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
