# Generated by Django 3.2.23 on 2024-01-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
