# Generated by Django 3.2.23 on 2024-01-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_shippingaddress_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('aadharnumber', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
